version: 0.2
phases:
  install:
     runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre_build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd Authorization
      - mvn compile
      - mvn package
      - echo "building docker image"
      - docker build -t service/auditauthapp .
      - docker tag service/auditauthapp 885843804602.dkr.ecr.us-east-2.amazonaws.com/docker-audit-auth:auditauthapp
  post_build:
     commands:
      - echo "Entered the post-build phase"
      - docker push 885843804602.dkr.ecr.us-east-2.amazonaws.com/docker-audit-auth:auditauthapp
      - printf '[{"name":"auditauthapp-container-audit","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-2.amazonaws.com/docker-audit-auth:auditauthapp > taskdefinition.json
artifacts:
  files:
    - Authorization/taskdefinition.json